// This file was generated by Mendix Business Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package communitycommons.actions;

import com.mendix.core.Core;
import com.mendix.logging.ILogNode;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import com.mendix.systemwideinterfaces.core.IMendixObject;

/**
 * Compare 2 objects an assert if they are the same.
 */
public class DeepObjectAssert extends CustomJavaAction<Boolean>
{
	private IMendixObject ExpectedObject;
	private IMendixObject ActualObject;

	public DeepObjectAssert(IContext context, IMendixObject ExpectedObject, IMendixObject ActualObject)
	{
		super(context);
		this.ExpectedObject = ExpectedObject;
		this.ActualObject = ActualObject;
	}

	@Override
	public Boolean executeAction() throws Exception
	{
		// BEGIN USER CODE
		ILogNode logger = Core.getLogger("DeepObjectAssert");
		Comparator comparator = new Comparator(ExpectedObject, ActualObject, getContext(), logger);

		return comparator.CompareLists();
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@Override
	public String toString()
	{
		return "DeepObjectAssert";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
