// This file was generated by Mendix Modeler 7.23.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package communitycommons.proxies.constants;

import com.mendix.core.Core;

public class Constants
{
	// These are the constants for the CommunityCommons module

	/**
	* Restricted to 10 files at once for Mendix Cloud v4 compatibility. If you need to merge more than 10 files increase the number here. Setting the value to <=0 means unlimited.
	* 
	* Note: We very strongly recommend to not increase the number for applications running in Mendix Cloud v4.
	*/
	public static java.lang.Long getMergeMultiplePdfs_MaxAtOnce()
	{
		return (java.lang.Long)Core.getConfiguration().getConstantValue("CommunityCommons.MergeMultiplePdfs_MaxAtOnce");
	}
}