// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package objecthandling.actions;

import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import com.mendix.systemwideinterfaces.core.IMendixObject;

/**
 * Deletes the given objects from the database and server cache (synchronously) without events This action is executed in a transaction.
 */
public class deleteWithoutEvents extends CustomJavaAction<Boolean>
{
	private java.util.List<IMendixObject> objectList;
	private Boolean useDeleteBehavior;

	public deleteWithoutEvents(IContext context, java.util.List<IMendixObject> objectList, Boolean useDeleteBehavior)
	{
		super(context);
		this.objectList = objectList;
		this.useDeleteBehavior = useDeleteBehavior;
	}

	@Override
	public Boolean executeAction() throws Exception
	{
		// BEGIN USER CODE
		Core.deleteWithoutEvents(getContext(), objectList, useDeleteBehavior);
		return true;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@Override
	public String toString()
	{
		return "deleteWithoutEvents";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
