// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package myfirstmodule.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import java.io.ByteArrayInputStream;
import java.io.InputStream;
import java.nio.charset.StandardCharsets;
import java.util.UUID;
import communitycommons.ORM;
import system.proxies.FileDocument;
import com.mendix.systemwideinterfaces.core.UserAction;

public class Test_Clone_Java extends UserAction<java.lang.Boolean>
{
	public Test_Clone_Java(IContext context)
	{
		super(context);
	}

	@java.lang.Override
	public java.lang.Boolean executeAction() throws Exception
	{
		// BEGIN USER CODE
		FileDocument doc = new FileDocument(getContext());
		doc.setName("TestDocument");
		doc.getMendixObject().setValue(getContext(), "__UUID__", UUID.randomUUID().toString());
		InputStream is = new ByteArrayInputStream("foo".getBytes(StandardCharsets.UTF_8));
		doc.getMendixObject().setValue(getContext(), FileDocument.MemberNames.Contents.toString(), is);
		doc.commit(getContext());

		FileDocument clonedDoc = new FileDocument(getContext());
		ORM.cloneObject(getContext(), doc.getMendixObject(), clonedDoc.getMendixObject(), false);
		clonedDoc.commit(getContext());

		if (!clonedDoc.getName().equals(doc.getName())) throw new RuntimeException("Name was not cloned.");
		if (getUUID(doc).equals(getUUID(clonedDoc))) throw new RuntimeException("UUID was cloned.");

		return true;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "Test_Clone_Java";
	}

	// BEGIN EXTRA CODE
	public Object getUUID(FileDocument doc) {
		return doc.getMendixObject().getValue(getContext(), "__UUID__");
	}
	// END EXTRA CODE
}
