// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package communitycommons.proxies;

public enum SanitizerPolicy
{
	BLOCKS(new String[][] { new String[] { "en_US", "BLOCKS" } }),
	FORMATTING(new String[][] { new String[] { "en_US", "FORMATTING" } }),
	IMAGES(new String[][] { new String[] { "en_US", "IMAGES" } }),
	LINKS(new String[][] { new String[] { "en_US", "LINKS" } }),
	STYLES(new String[][] { new String[] { "en_US", "STYLES" } }),
	TABLES(new String[][] { new String[] { "en_US", "TABLES" } });

	private java.util.Map<String,String> captions;

	private SanitizerPolicy(String[][] captionStrings)
	{
		this.captions = new java.util.HashMap<String,String>();
		for (String[] captionString : captionStrings)
			captions.put(captionString[0], captionString[1]);
	}

	public String getCaption(String languageCode)
	{
		if (captions.containsKey(languageCode))
			return captions.get(languageCode);
		return captions.get("en_US");
	}

	public String getCaption()
	{
		return captions.get("en_US");
	}
}
