// This file was generated by Mendix Modeler 6.0.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package communitycommons.proxies.constants;

import com.mendix.core.Core;

public class Constants
{
	// These are the constants for the CommunityCommons module

	public static boolean getenableReleaseLockEvent()
	{
		return (Boolean)Core.getConfiguration().getConstantValue("CommunityCommons.enableReleaseLockEvent");
	}
}