// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies;

public class GeolocationHelper
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject geolocationHelperMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MyFirstModule.GeolocationHelper";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		LatitudeBase("LatitudeBase"),
		LongitudeBase("LongitudeBase"),
		LatitudeToCompare("LatitudeToCompare"),
		LongitudeToCompare("LongitudeToCompare");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public GeolocationHelper(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "MyFirstModule.GeolocationHelper"));
	}

	protected GeolocationHelper(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject geolocationHelperMendixObject)
	{
		if (geolocationHelperMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("MyFirstModule.GeolocationHelper", geolocationHelperMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a MyFirstModule.GeolocationHelper");

		this.geolocationHelperMendixObject = geolocationHelperMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'GeolocationHelper.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static myfirstmodule.proxies.GeolocationHelper initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return myfirstmodule.proxies.GeolocationHelper.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static myfirstmodule.proxies.GeolocationHelper initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new myfirstmodule.proxies.GeolocationHelper(context, mendixObject);
	}

	public static myfirstmodule.proxies.GeolocationHelper load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return myfirstmodule.proxies.GeolocationHelper.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of LatitudeBase
	 */
	public final java.math.BigDecimal getLatitudeBase()
	{
		return getLatitudeBase(getContext());
	}

	/**
	 * @param context
	 * @return value of LatitudeBase
	 */
	public final java.math.BigDecimal getLatitudeBase(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.LatitudeBase.toString());
	}

	/**
	 * Set value of LatitudeBase
	 * @param latitudebase
	 */
	public final void setLatitudeBase(java.math.BigDecimal latitudebase)
	{
		setLatitudeBase(getContext(), latitudebase);
	}

	/**
	 * Set value of LatitudeBase
	 * @param context
	 * @param latitudebase
	 */
	public final void setLatitudeBase(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal latitudebase)
	{
		getMendixObject().setValue(context, MemberNames.LatitudeBase.toString(), latitudebase);
	}

	/**
	 * @return value of LongitudeBase
	 */
	public final java.math.BigDecimal getLongitudeBase()
	{
		return getLongitudeBase(getContext());
	}

	/**
	 * @param context
	 * @return value of LongitudeBase
	 */
	public final java.math.BigDecimal getLongitudeBase(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.LongitudeBase.toString());
	}

	/**
	 * Set value of LongitudeBase
	 * @param longitudebase
	 */
	public final void setLongitudeBase(java.math.BigDecimal longitudebase)
	{
		setLongitudeBase(getContext(), longitudebase);
	}

	/**
	 * Set value of LongitudeBase
	 * @param context
	 * @param longitudebase
	 */
	public final void setLongitudeBase(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal longitudebase)
	{
		getMendixObject().setValue(context, MemberNames.LongitudeBase.toString(), longitudebase);
	}

	/**
	 * @return value of LatitudeToCompare
	 */
	public final java.math.BigDecimal getLatitudeToCompare()
	{
		return getLatitudeToCompare(getContext());
	}

	/**
	 * @param context
	 * @return value of LatitudeToCompare
	 */
	public final java.math.BigDecimal getLatitudeToCompare(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.LatitudeToCompare.toString());
	}

	/**
	 * Set value of LatitudeToCompare
	 * @param latitudetocompare
	 */
	public final void setLatitudeToCompare(java.math.BigDecimal latitudetocompare)
	{
		setLatitudeToCompare(getContext(), latitudetocompare);
	}

	/**
	 * Set value of LatitudeToCompare
	 * @param context
	 * @param latitudetocompare
	 */
	public final void setLatitudeToCompare(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal latitudetocompare)
	{
		getMendixObject().setValue(context, MemberNames.LatitudeToCompare.toString(), latitudetocompare);
	}

	/**
	 * @return value of LongitudeToCompare
	 */
	public final java.math.BigDecimal getLongitudeToCompare()
	{
		return getLongitudeToCompare(getContext());
	}

	/**
	 * @param context
	 * @return value of LongitudeToCompare
	 */
	public final java.math.BigDecimal getLongitudeToCompare(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.LongitudeToCompare.toString());
	}

	/**
	 * Set value of LongitudeToCompare
	 * @param longitudetocompare
	 */
	public final void setLongitudeToCompare(java.math.BigDecimal longitudetocompare)
	{
		setLongitudeToCompare(getContext(), longitudetocompare);
	}

	/**
	 * Set value of LongitudeToCompare
	 * @param context
	 * @param longitudetocompare
	 */
	public final void setLongitudeToCompare(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal longitudetocompare)
	{
		getMendixObject().setValue(context, MemberNames.LongitudeToCompare.toString(), longitudetocompare);
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return geolocationHelperMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final myfirstmodule.proxies.GeolocationHelper that = (myfirstmodule.proxies.GeolocationHelper) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "MyFirstModule.GeolocationHelper";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
