// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies;

public class StringFromFile extends system.proxies.FileDocument
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MyFirstModule.StringFromFile";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		ContentAsString("ContentAsString"),
		Encoding("Encoding"),
		FileID("FileID"),
		Name("Name"),
		DeleteAfterDownload("DeleteAfterDownload"),
		Contents("Contents"),
		HasContents("HasContents"),
		Size("Size");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public StringFromFile(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected StringFromFile(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject stringFromFileMendixObject)
	{
		super(context, stringFromFileMendixObject);
		if (!com.mendix.core.Core.isSubClassOf(entityName, stringFromFileMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	
	}

	/**
	 * @deprecated Use 'StringFromFile.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static myfirstmodule.proxies.StringFromFile initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return myfirstmodule.proxies.StringFromFile.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static myfirstmodule.proxies.StringFromFile initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new myfirstmodule.proxies.StringFromFile(context, mendixObject);
	}

	public static myfirstmodule.proxies.StringFromFile load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return myfirstmodule.proxies.StringFromFile.initialize(context, mendixObject);
	}

	public static java.util.List<myfirstmodule.proxies.StringFromFile> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> myfirstmodule.proxies.StringFromFile.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * @return value of ContentAsString
	 */
	public final java.lang.String getContentAsString()
	{
		return getContentAsString(getContext());
	}

	/**
	 * @param context
	 * @return value of ContentAsString
	 */
	public final java.lang.String getContentAsString(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ContentAsString.toString());
	}

	/**
	 * Set value of ContentAsString
	 * @param contentasstring
	 */
	public final void setContentAsString(java.lang.String contentasstring)
	{
		setContentAsString(getContext(), contentasstring);
	}

	/**
	 * Set value of ContentAsString
	 * @param context
	 * @param contentasstring
	 */
	public final void setContentAsString(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String contentasstring)
	{
		getMendixObject().setValue(context, MemberNames.ContentAsString.toString(), contentasstring);
	}

	/**
	 * Set value of Encoding
	 * @param encoding
	 */
	public final communitycommons.proxies.StandardEncodings getEncoding()
	{
		return getEncoding(getContext());
	}

	/**
	 * @param context
	 * @return value of Encoding
	 */
	public final communitycommons.proxies.StandardEncodings getEncoding(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.Encoding.toString());
		if (obj == null) {
			return null;
		}
		return communitycommons.proxies.StandardEncodings.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of Encoding
	 * @param encoding
	 */
	public final void setEncoding(communitycommons.proxies.StandardEncodings encoding)
	{
		setEncoding(getContext(), encoding);
	}

	/**
	 * Set value of Encoding
	 * @param context
	 * @param encoding
	 */
	public final void setEncoding(com.mendix.systemwideinterfaces.core.IContext context, communitycommons.proxies.StandardEncodings encoding)
	{
		if (encoding != null) {
			getMendixObject().setValue(context, MemberNames.Encoding.toString(), encoding.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.Encoding.toString(), null);
		}
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final myfirstmodule.proxies.StringFromFile that = (myfirstmodule.proxies.StringFromFile) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return entityName;
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Override
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
