// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies;

public class VersionInfo
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject versionInfoMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MyFirstModule.VersionInfo";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		ModelVersion("ModelVersion"),
		RuntimeVersion("RuntimeVersion");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public VersionInfo(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "MyFirstModule.VersionInfo"));
	}

	protected VersionInfo(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject versionInfoMendixObject)
	{
		if (versionInfoMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("MyFirstModule.VersionInfo", versionInfoMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a MyFirstModule.VersionInfo");

		this.versionInfoMendixObject = versionInfoMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'VersionInfo.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static myfirstmodule.proxies.VersionInfo initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return myfirstmodule.proxies.VersionInfo.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static myfirstmodule.proxies.VersionInfo initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new myfirstmodule.proxies.VersionInfo(context, mendixObject);
	}

	public static myfirstmodule.proxies.VersionInfo load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return myfirstmodule.proxies.VersionInfo.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of ModelVersion
	 */
	public final java.lang.String getModelVersion()
	{
		return getModelVersion(getContext());
	}

	/**
	 * @param context
	 * @return value of ModelVersion
	 */
	public final java.lang.String getModelVersion(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ModelVersion.toString());
	}

	/**
	 * Set value of ModelVersion
	 * @param modelversion
	 */
	public final void setModelVersion(java.lang.String modelversion)
	{
		setModelVersion(getContext(), modelversion);
	}

	/**
	 * Set value of ModelVersion
	 * @param context
	 * @param modelversion
	 */
	public final void setModelVersion(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String modelversion)
	{
		getMendixObject().setValue(context, MemberNames.ModelVersion.toString(), modelversion);
	}

	/**
	 * @return value of RuntimeVersion
	 */
	public final java.lang.String getRuntimeVersion()
	{
		return getRuntimeVersion(getContext());
	}

	/**
	 * @param context
	 * @return value of RuntimeVersion
	 */
	public final java.lang.String getRuntimeVersion(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.RuntimeVersion.toString());
	}

	/**
	 * Set value of RuntimeVersion
	 * @param runtimeversion
	 */
	public final void setRuntimeVersion(java.lang.String runtimeversion)
	{
		setRuntimeVersion(getContext(), runtimeversion);
	}

	/**
	 * Set value of RuntimeVersion
	 * @param context
	 * @param runtimeversion
	 */
	public final void setRuntimeVersion(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String runtimeversion)
	{
		getMendixObject().setValue(context, MemberNames.RuntimeVersion.toString(), runtimeversion);
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return versionInfoMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final myfirstmodule.proxies.VersionInfo that = (myfirstmodule.proxies.VersionInfo) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "MyFirstModule.VersionInfo";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
