// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package communitycommons.proxies;

public enum LogLevel
{
	Trace(new String[][] { new String[] { "en_US", "Trace" }, new String[] { "nl_NL", "Trace" } }),
	Debug(new String[][] { new String[] { "en_US", "Debug" }, new String[] { "nl_NL", "Debug" } }),
	Info(new String[][] { new String[] { "en_US", "Info" }, new String[] { "nl_NL", "Info" } }),
	Warning(new String[][] { new String[] { "en_US", "Warning" }, new String[] { "nl_NL", "Warning" } }),
	Error(new String[][] { new String[] { "en_US", "Error" }, new String[] { "nl_NL", "Error" } }),
	Critical(new String[][] { new String[] { "en_US", "Critical" }, new String[] { "nl_NL", "Critical" } });

	private java.util.Map<String,String> captions;

	private LogLevel(String[][] captionStrings)
	{
		this.captions = new java.util.HashMap<String,String>();
		for (String[] captionString : captionStrings)
			captions.put(captionString[0], captionString[1]);
	}

	public String getCaption(String languageCode)
	{
		if (captions.containsKey(languageCode))
			return captions.get(languageCode);
		return captions.get("en_US");
	}

	public String getCaption()
	{
		return captions.get("en_US");
	}
}
