// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package communitycommons.actions;

import com.mendix.systemwideinterfaces.core.IMendixObject;
import communitycommons.StringUtils;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import com.mendix.systemwideinterfaces.core.UserAction;

/**
 * Converts an unencoded file to a base 64 encoded string.
 */
public class Base64EncodeFile extends UserAction<java.lang.String>
{
	/** @deprecated use file.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __file;
	private final system.proxies.FileDocument file;

	public Base64EncodeFile(
		IContext context,
		IMendixObject _file
	)
	{
		super(context);
		this.__file = _file;
		this.file = _file == null ? null : system.proxies.FileDocument.initialize(getContext(), _file);
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		// BEGIN USER CODE
		return StringUtils.base64EncodeFile(getContext(), file);
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "Base64EncodeFile";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
