// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package communitycommons.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import communitycommons.Logging;
import com.mendix.systemwideinterfaces.core.UserAction;

/**
 * Initializes a log node for later use. Useful to set logging to a more detailed log level before the first time a certain log action is executed.
 */
public class CreateLogNode extends UserAction<java.lang.Boolean>
{
	private final java.lang.String logNodeParameter;

	public CreateLogNode(
		IContext context,
		java.lang.String _logNodeParameter
	)
	{
		super(context);
		this.logNodeParameter = _logNodeParameter;
	}

	@java.lang.Override
	public java.lang.Boolean executeAction() throws Exception
	{
		// BEGIN USER CODE
		Logging.createLogNode(logNodeParameter);
		return true;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "CreateLogNode";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
