// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package communitycommons.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import communitycommons.XPath;
import com.mendix.systemwideinterfaces.core.UserAction;

/**
 * Removes ALL instances of a certain domain object type using batches.
 */
public class deleteAll extends UserAction<java.lang.Boolean>
{
	private final java.lang.String entityType;

	public deleteAll(
		IContext context,
		java.lang.String _entityType
	)
	{
		super(context);
		this.entityType = _entityType;
	}

	@java.lang.Override
	public java.lang.Boolean executeAction() throws Exception
	{
		// BEGIN USER CODE
		return XPath.create(this.getContext(), entityType).deleteAll();
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "deleteAll";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
