// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package communitycommons.actions;

import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import com.mendix.systemwideinterfaces.core.IMendixObject;

/**
 * This action will invoke a microflow, optionally with an argument and/or return value.
 * It will execute the microflow in the system context.
 * This is useful when performing a lot of changes and avoiding the overhead of the user context which will send updates/changes back to the client.
 * A must have for > 100k updates.
 */
public class executeMicroflowAsSystemUser extends CustomJavaAction<IMendixObject>
{
	private java.lang.String microflow;
	private java.lang.String microflowArgumentEntity;
	private IMendixObject microflowArgument;
	private java.lang.String microflowReturnType;

	public executeMicroflowAsSystemUser(IContext context, java.lang.String microflow, java.lang.String microflowArgumentEntity, IMendixObject microflowArgument, java.lang.String microflowReturnType)
	{
		super(context);
		this.microflow = microflow;
		this.microflowArgumentEntity = microflowArgumentEntity;
		this.microflowArgument = microflowArgument;
		this.microflowReturnType = microflowReturnType;
	}

	@java.lang.Override
	public IMendixObject executeAction() throws Exception
	{
		// BEGIN USER CODE
		IMendixObject result = null;
		IContext sysContext = Core.createSystemContext();
		sysContext.startTransaction();
		try {
			Object r;
			if (this.microflowArgument != null) {
				r = Core.execute(sysContext, microflow, microflowArgument);
			} else {
				r = Core.execute(sysContext, microflow); 
			}
			if (r != null && r instanceof IMendixObject) {
				result = (IMendixObject) r;
			}
		} finally {
			while (sysContext.isInTransaction()) {
				sysContext.endTransaction();
			}
		}
		return result;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "executeMicroflowAsSystemUser";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
