// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package communitycommons.actions;

import java.io.File;
import java.io.FileOutputStream;
import java.io.InputStream;
import org.apache.commons.io.IOUtils;
import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.systemwideinterfaces.core.UserAction;

/**
 * Reads contents from a FileDocument and stores it in a file on the local (server) storage.
 */
public class FileFromFileDocument extends UserAction<java.lang.Boolean>
{
	private final java.lang.String targetFile;
	/** @deprecated use fileDocument.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __fileDocument;
	private final system.proxies.FileDocument fileDocument;

	public FileFromFileDocument(
		IContext context,
		java.lang.String _targetFile,
		IMendixObject _fileDocument
	)
	{
		super(context);
		this.targetFile = _targetFile;
		this.__fileDocument = _fileDocument;
		this.fileDocument = _fileDocument == null ? null : system.proxies.FileDocument.initialize(getContext(), _fileDocument);
	}

	@java.lang.Override
	public java.lang.Boolean executeAction() throws Exception
	{
		// BEGIN USER CODE
		File output = new File(targetFile);
		
		try (
			FileOutputStream fos = new FileOutputStream(output);
			InputStream is = Core.getFileDocumentContent(getContext(), fileDocument.getMendixObject());
		) {
			IOUtils.copy(is, fos);
		}
		
		return true;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "FileFromFileDocument";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
