// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package communitycommons.actions;

import com.mendix.systemwideinterfaces.core.IMendixObject;
import communitycommons.Misc;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import com.mendix.systemwideinterfaces.core.UserAction;

/**
 * Returns the filesize of a file document in bytes.
 * 
 * From version 2.3 on, this function can be used in cloud environments as well. 
 * 
 * NOTE:
 * before 2.1, this functioned returned the size in kilobytes, although this documentation mentioned bytes
 */
public class getFileSize extends UserAction<java.lang.Long>
{
	/** @deprecated use document.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __document;
	private final system.proxies.FileDocument document;

	public getFileSize(
		IContext context,
		IMendixObject _document
	)
	{
		super(context);
		this.__document = _document;
		this.document = _document == null ? null : system.proxies.FileDocument.initialize(getContext(), _document);
	}

	@java.lang.Override
	public java.lang.Long executeAction() throws Exception
	{
		// BEGIN USER CODE
		return Misc.getFileSize(this.getContext(), document.getMendixObject());
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "getFileSize";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
