// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package communitycommons.actions;

import java.io.File;
import java.io.FileInputStream;
import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.systemwideinterfaces.core.UserAction;

/**
 * Set the contents of a FileDocument with the contents of a file which is a resource.
 */
public class GetFileContentsFromResource extends UserAction<java.lang.Boolean>
{
	private final java.lang.String filename;
	/** @deprecated use fileDocument.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __fileDocument;
	private final system.proxies.FileDocument fileDocument;

	public GetFileContentsFromResource(
		IContext context,
		java.lang.String _filename,
		IMendixObject _fileDocument
	)
	{
		super(context);
		this.filename = _filename;
		this.__fileDocument = _fileDocument;
		this.fileDocument = _fileDocument == null ? null : system.proxies.FileDocument.initialize(getContext(), _fileDocument);
	}

	@java.lang.Override
	public java.lang.Boolean executeAction() throws Exception
	{
		// BEGIN USER CODE
		File myFile = new File(Core.getConfiguration().getResourcesPath() + 
				File.separator + filename);

		try (
			FileInputStream fis = new FileInputStream(myFile)
		) {
			Core.storeFileDocumentContent(getContext(), fileDocument.getMendixObject(), filename, fis);
		}
		
		return true;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "GetFileContentsFromResource";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
