// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package communitycommons.actions;

import javax.imageio.ImageIO;
import javax.imageio.ImageReader;
import javax.imageio.stream.ImageInputStream;
import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.webui.CustomJavaAction;
import communitycommons.proxies.ImageDimensions;
import java.io.IOException;
import java.io.InputStream;
import java.util.Iterator;

public class GetImageDimensions extends CustomJavaAction<IMendixObject>
{
	private IMendixObject __ImageParameter;
	private system.proxies.Image ImageParameter;

	public GetImageDimensions(IContext context, IMendixObject ImageParameter)
	{
		super(context);
		this.__ImageParameter = ImageParameter;
	}

	@java.lang.Override
	public IMendixObject executeAction() throws Exception
	{
		this.ImageParameter = this.__ImageParameter == null ? null : system.proxies.Image.initialize(getContext(), __ImageParameter);

		// BEGIN USER CODE
		ImageDimensions imageDimensions = new ImageDimensions(getContext());

		try (InputStream inputStream = Core.getImage(getContext(), this.ImageParameter.getMendixObject(), false);
			ImageInputStream imageStream = ImageIO.createImageInputStream(inputStream)) {
			if(imageStream != null) {
				Iterator<ImageReader> readers = ImageIO.getImageReaders(imageStream);
				if (!readers.hasNext()) throw new IOException("Can't find a suitable imagereader for this image");;

				ImageReader reader = readers.next();
			  
				try {
					reader.setInput(imageStream);
					int height = reader.getHeight(reader.getMinIndex());
					int width = reader.getWidth(reader.getMinIndex());
					imageDimensions.setHeight(height);
					imageDimensions.setWidth(width);
					return imageDimensions.getMendixObject();
				} finally {
					reader.dispose();
				}
			} else {
				throw new IOException("Can't open a stream for this image");
			}
		}
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "GetImageDimensions";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
