// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package communitycommons.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import communitycommons.DateTime;
import com.mendix.systemwideinterfaces.core.UserAction;

/**
 * Converts a datetime to an integer based on the selector used.
 * 
 * Selectors available are:
 * - year (returns f. ex. 1980)
 * - month (returns 1-12)
 * - day (returns 1-31)
 */
public class GetIntFromDateTime extends UserAction<java.lang.Long>
{
	private final java.util.Date dateObj;
	private final communitycommons.proxies.DatePartSelector selectorObj;

	public GetIntFromDateTime(
		IContext context,
		java.util.Date _dateObj,
		java.lang.String _selectorObj
	)
	{
		super(context);
		this.dateObj = _dateObj;
		this.selectorObj = _selectorObj == null ? null : communitycommons.proxies.DatePartSelector.valueOf(_selectorObj);
	}

	@java.lang.Override
	public java.lang.Long executeAction() throws Exception
	{
		// BEGIN USER CODE
		return DateTime.dateTimeToInteger(dateObj, selectorObj);
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "GetIntFromDateTime";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
