// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package communitycommons.actions;

import communitycommons.StringUtils;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.UserAction;

/**
 * Hashes a value using the SHA-256 hash algorithm. 
 * 
 * - value : the value to hash
 * 
 * Returns a SHA-256 hash of 'value'
 */
public class Hash extends UserAction<java.lang.String>
{
	private final java.lang.String value;
	private final java.lang.Long length;

	public Hash(
		IContext context,
		java.lang.String _value,
		java.lang.Long _length
	)
	{
		super(context);
		this.value = _value;
		this.length = _length;
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		// BEGIN USER CODE
		return StringUtils.hash(value);
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "Hash";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
