// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package communitycommons.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class ListStringJoiner extends CustomJavaAction<java.lang.String>
{
	private java.lang.String joinerMemberName;
	private java.lang.String separator;
	private java.util.List<IMendixObject> inputList;

	public ListStringJoiner(IContext context, java.lang.String joinerMemberName, java.lang.String separator, java.util.List<IMendixObject> inputList)
	{
		super(context);
		this.joinerMemberName = joinerMemberName;
		this.separator = separator;
		this.inputList = inputList;
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		// BEGIN USER CODE
        if (inputList == null || inputList.isEmpty()) {
            throw new IllegalArgumentException("The input list is empty.");
        }

        StringBuilder result = new StringBuilder();

        for (IMendixObject obj : inputList) {
            try {
                String memberValue = (String) obj.getValue(getContext(), joinerMemberName);
                if (memberValue != null && !memberValue.isEmpty()) {
                    result.append(memberValue);
                    result.append(separator);
                }
            } catch (Exception e) {
                throw new IllegalArgumentException("Invalid attribute name: " + joinerMemberName);
            }
        }

        if (result.length() > 0) {
            result.setLength(result.length() - separator.length());
        }

        return result.toString();
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "ListStringJoiner";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
