// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package communitycommons.actions;

import com.mendix.systemwideinterfaces.core.IMendixObject;
import communitycommons.ORM;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.UserAction;

/**
 * Check if the value of the member was changed to something other than its original value.
 */
public class memberHasChangedValue extends UserAction<java.lang.Boolean>
{
	private final IMendixObject item;
	private final java.lang.String member;

	public memberHasChangedValue(
		IContext context,
		IMendixObject _item,
		java.lang.String _member
	)
	{
		super(context);
		this.item = _item;
		this.member = _member;
	}

	@java.lang.Override
	public java.lang.Boolean executeAction() throws Exception
	{
		// BEGIN USER CODE
		return ORM.memberHasChangedValue(getContext(), item, member);
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "memberHasChangedValue";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
