// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package communitycommons.actions;

import com.mendix.systemwideinterfaces.core.IMendixObject;
import communitycommons.ORM;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;

/**
 * Returns true if any member has a value other than its original value.
 */
public class objectHasChangedMemberValue extends CustomJavaAction<java.lang.Boolean>
{
	private IMendixObject item;

	public objectHasChangedMemberValue(IContext context, IMendixObject item)
	{
		super(context);
		this.item = item;
	}

	@java.lang.Override
	public java.lang.Boolean executeAction() throws Exception
	{
		// BEGIN USER CODE
		return ORM.objectHasChangedMemberValue(getContext(), item);
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "objectHasChangedMemberValue";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
