// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package communitycommons.actions;

import communitycommons.Misc;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import com.mendix.systemwideinterfaces.core.UserAction;

public class recommitInBatches extends UserAction<java.lang.Boolean>
{
	private final java.lang.String xpath;
	private final java.lang.Long batchsize;
	private final java.lang.Boolean waitUntilFinished;
	private final java.lang.Boolean ascending;

	public recommitInBatches(
		IContext context,
		java.lang.String _xpath,
		java.lang.Long _batchsize,
		java.lang.Boolean _waitUntilFinished,
		java.lang.Boolean _ascending
	)
	{
		super(context);
		this.xpath = _xpath;
		this.batchsize = _batchsize;
		this.waitUntilFinished = _waitUntilFinished;
		this.ascending = _ascending;
	}

	@java.lang.Override
	public java.lang.Boolean executeAction() throws Exception
	{
		// BEGIN USER CODE
		return Misc.recommitInBatches(xpath, batchsize.intValue(), waitUntilFinished.booleanValue(), ascending);
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "recommitInBatches";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
