// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package communitycommons.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import com.mendix.systemwideinterfaces.core.IMendixObject;

/**
 * This Java action is able to take a generic input list from any entity, and return a reversed list for the list entered in the parameters.
 */
public class ReverseList extends CustomJavaAction<java.util.List<IMendixObject>>
{
	private java.util.List<IMendixObject> InputList;

	public ReverseList(IContext context, java.util.List<IMendixObject> InputList)
	{
		super(context);
		this.InputList = InputList;
	}

	@java.lang.Override
	public java.util.List<IMendixObject> executeAction() throws Exception
	{
		// BEGIN USER CODE
        for(int i = 0, j = InputList.size() - 1; i < j; i++) {
            InputList.add(i, InputList.remove(j));
        }
        return InputList;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "ReverseList";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
