// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package communitycommons.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import communitycommons.StringUtils;
import com.mendix.systemwideinterfaces.core.UserAction;

/**
 * Gets the substring after the first occurrence of a separator.
 */
public class SubstringAfter extends UserAction<java.lang.String>
{
	private final java.lang.String str;
	private final java.lang.String separator;

	public SubstringAfter(
		IContext context,
		java.lang.String _str,
		java.lang.String _separator
	)
	{
		super(context);
		this.str = _str;
		this.separator = _separator;
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		// BEGIN USER CODE
		return StringUtils.substringAfter(str, separator);
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "SubstringAfter";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
