// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package communitycommons.actions;

import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class UniqueList extends CustomJavaAction<java.util.List<IMendixObject>>
{
	private java.lang.String primaryIDMemberName;
	private java.util.List<IMendixObject> inputList;

	public UniqueList(IContext context, java.lang.String primaryIDMemberName, java.util.List<IMendixObject> inputList)
	{
		super(context);
		this.primaryIDMemberName = primaryIDMemberName;
		this.inputList = inputList;
	}

	@java.lang.Override
	public java.util.List<IMendixObject> executeAction() throws Exception
	{
		// BEGIN USER CODE
		if (inputList == null || inputList.isEmpty()) {
			throw new IllegalArgumentException("The object list is empty.");
		}
		
		Set<String> uniquePrimaryIDs = new HashSet<>();
		List<IMendixObject> uniqueObjects = new ArrayList<>();

		for (IMendixObject obj : inputList) {
			try {
				String primaryIDValue = obj.getValue(getContext(), primaryIDMemberName).toString();
				if (!uniquePrimaryIDs.contains(primaryIDValue)) {
					uniquePrimaryIDs.add(primaryIDValue);
					uniqueObjects.add(obj);
				}
			} catch (Exception e) {
				throw new IllegalArgumentException("Invalid attribute name: " + primaryIDMemberName);
			}
		}

		return uniqueObjects;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "UniqueList";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
